function createfigure(X1, YMatrix1, YMatrix2, YMatrix3)
%CREATEFIGURE(X1, YMatrix1, YMatrix2, YMatrix3)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  YMATRIX2:  matrix of plot y data
%  YMATRIX3:  matrix of plot y data

%  Auto-generated by MATLAB on 02-Nov-2023 09:54:55

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1);
set(plot1(1),'DisplayName','ego','Color',[1 0 0]);
set(plot1(2),'DisplayName','lead','Color',[0 0 1]);

% Create ylabel
ylabel('$m/s^2$','Interpreter','latex');

% Create xlabel
xlabel('time (sec)');

% Create title
title('Acceleration');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-3.2 2.2]);
box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'off');
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'Location','southeast');

% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple line objects using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2);
set(plot2(1),'DisplayName','ego','Color',[1 0 0]);
set(plot2(2),'DisplayName','lead','Color',[0 0 1]);
set(plot2(3),'DisplayName','set','LineStyle','--','Color',[0 0 0]);

% Create ylabel
ylabel('$m/s$','Interpreter','latex');

% Create xlabel
xlabel('time (sec)');

% Create title
title('Velocity');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[15 35]);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'off');
% Create legend
legend2 = legend(subplot2,'show');
set(legend2,'Location','southeast');

% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create multiple line objects using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',subplot3);
set(plot3(1),'DisplayName','actual','Color',[1 0 0]);
set(plot3(2),'DisplayName','safe','Color',[0 0 1]);

% Create ylabel
ylabel('$m$','Interpreter','latex');

% Create xlabel
xlabel('time (sec)');

% Create title
title('Distance between two cars');

box(subplot3,'on');
grid(subplot3,'on');
hold(subplot3,'off');
% Create legend
legend3 = legend(subplot3,'show');
set(legend3,'Location','southeast');

